### ISSUE TITLE
TensorFlow Error while Using Machine Translator

### ISSUE THREAD

**Issue by Neetesh988** [Neetesh988/Tensorflow#1]
Traceback (most recent call last):
  File "translate.py", line 271, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "translate.py", line 267, in main
    testBLEU()
  File "translate.py", line 206, in testBLEU
    model = create_model(sess, True, True)
  File "translate.py", line 98, in create_model
    dtype=dtype)
  File "/home/shri/Downloads/How_to_make_a_language_translator-master/seq2seq_model.py", line 98, in __init__
    w_t = tf.get_variable("proj_w", [self.target_vocab_size, size], dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 632, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable proj_w already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/shri/Downloads/How_to_make_a_language_translator-master/seq2seq_model.py", line 98, in __init__
    w_t = tf.get_variable("proj_w", [self.target_vocab_size, size], dtype=dtype)
  File "translate.py", line 98, in create_model
    dtype=dtype)
  File "translate.py", line 122, in train
    model = create_model(sess, False, False)

**Comment by ganesha1994** [comment]
Go get some sleep bro.
